---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-${MOLECULE_DISTRO:-debian11}-ansible:latest
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: True
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    links:
      host_vars: inventory/host_vars
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8
